DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    balance INT DEFAULT 0,
    xp INT DEFAULT 0,
    fish INT DEFAULT 0
);

DROP TABLE IF EXISTS items;

CREATE TABLE items (
    id VARCHAR(16) PRIMARY KEY,
    owner_id BIGINT NOT NUll,
    item INT NOT NULL,
    rating SMALLINT NOT NULL
);